name: Deploy to DigitalOcean

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DO_SSH_KEY }}

      - name: Add GitHub to known_hosts (ensure SSH connection to GitHub)
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Add DigitalOcean server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan 46.101.222.112 >> ~/.ssh/known_hosts

      - name: Determine the branch to deploy
        id: deploy_branch
        run: |
          echo "Deploying to branch: $GITHUB_REF"
          if [[ "$GITHUB_REF" == "refs/heads/staging" ]]; then
            echo "BRANCH=staging" >> $GITHUB_ENV
            echo "DEPLOY_PATH=/mnt/docker/php83/demo.imgglobal.in/fantasybox" >> $GITHUB_ENV
          elif [[ "$GITHUB_REF" == "refs/heads/staging111111" ]]; then
            echo "BRANCH=staging" >> $GITHUB_ENV
            echo "DEPLOY_PATH=/mnt/docker/php83/demo.imgglobal.in/healthfirstpharmacy" >> $GITHUB_ENV
          fi

      - name: Pull latest code on DigitalOcean server
        run: |
          ssh root@46.101.222.112 "cd ${{ env.DEPLOY_PATH }} && git pull origin ${{ env.BRANCH }} && \
          cd /mnt/docker && docker exec -t php83-app bash -c 'cd demo.imgglobal.in/fantasybox && composer install --no-dev --optimize-autoloader'"

